package bootstrap

import (
	"net/http"

	"github.com/labstack/echo/v4"

	"sansyar/backend/internal/auth"
	sansyarmw "sansyar/backend/pkg/middleware"
)

func (a *App) setupRoutes(e *echo.Echo) {
	e.GET("/health", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
	})

	api := e.Group("/api/v1")
	api.GET("/health", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
	})

	// Sensitive auth endpoints are rate limited per IP to blunt brute-force and
	// SMS-bombing.
	authLimit := sansyarmw.RateLimit(1, 8)
	api.POST("/auth/register", a.authHandler.Register, authLimit)
	api.POST("/auth/owner/register", a.authHandler.RegisterOwner, authLimit)
	api.POST("/auth/login", a.authHandler.Login, authLimit)
	api.POST("/auth/password/forgot", a.authHandler.ForgotPassword, authLimit)
	api.POST("/auth/password/reset", a.authHandler.ResetPassword, authLimit)
	api.POST("/auth/otp/request", a.authHandler.RequestOTP, authLimit)
	api.POST("/auth/otp/verify", a.authHandler.VerifyOTP)
	api.POST("/auth/refresh", a.authHandler.Refresh)
	api.POST("/auth/logout", a.authHandler.Logout)

	authenticated := api.Group("", sansyarmw.Auth(a.cfg.JWTSecret))
	authenticated.GET("/me", a.authHandler.Me)
	authenticated.PATCH("/me", a.authHandler.UpdateProfile)

	api.GET("/sports", a.sportHandler.List)
	api.GET("/provinces", a.locationHandler.List)
	api.GET("/stats", a.discoveryHandler.Stats)
	api.GET("/complexes", a.venueHandler.ListComplexes)
	api.GET("/complexes/featured", a.discoveryHandler.Featured)
	api.GET("/complexes/:id", a.venueHandler.GetComplex)
	api.GET("/complexes/:id/booking-count", a.discoveryHandler.BookingCount)
	api.GET("/complexes/:complexId/halls", a.venueHandler.ListHalls)
	api.GET("/halls/:id", a.venueHandler.GetHall)
	api.GET("/slots", a.venueHandler.ListSlots)
	api.GET("/halls/:hallId/slots", a.venueHandler.ListSlots)
	api.GET("/map/venues", a.venueHandler.MapVenues)
	api.GET("/complexes/:complexId/reviews", a.reviewHandler.List)
	api.POST("/support/tickets", a.supportHandler.Create, authLimit)

	// Store (sports shop) public catalog.
	api.GET("/store/products", a.storeHandler.ListProducts)
	api.GET("/store/products/:idOrSlug", a.storeHandler.GetProduct)
	api.GET("/store/categories", a.storeHandler.ListCategories)
	api.GET("/store/brands", a.storeHandler.ListBrands)

	// Cart: works for guests (X-Cart-Token) and customers; guest carts merge
	// into the user cart on the first authenticated request.
	storeCart := api.Group("", sansyarmw.OptionalAuth(a.cfg.JWTSecret))
	storeCart.GET("/store/cart", a.storeHandler.GetCart)
	storeCart.POST("/store/cart/items", a.storeHandler.AddCartItem)
	storeCart.PATCH("/store/cart/items/:variantId", a.storeHandler.UpdateCartItem)
	storeCart.DELETE("/store/cart/items/:variantId", a.storeHandler.RemoveCartItem)
	storeCart.DELETE("/store/cart", a.storeHandler.ClearCart)
	storeCart.POST("/store/cart/coupon", a.storeHandler.ApplyCoupon)
	storeCart.DELETE("/store/cart/coupon", a.storeHandler.RemoveCoupon)

	// Public store settings (shipping methods shown at checkout).
	api.GET("/store/settings", a.storeHandler.PublicSettings)

	// Checkout & orders require a customer (or admin) session.
	storeCustomer := api.Group("", sansyarmw.Auth(a.cfg.JWTSecret), sansyarmw.RequireRoles(auth.RoleCustomer, auth.RoleSuperAdmin))
	storeCustomer.GET("/store/addresses", a.storeHandler.ListAddresses)
	storeCustomer.POST("/store/addresses", a.storeHandler.CreateAddress)
	storeCustomer.PATCH("/store/addresses/:id", a.storeHandler.UpdateAddress)
	storeCustomer.DELETE("/store/addresses/:id", a.storeHandler.DeleteAddress)
	storeCustomer.POST("/store/checkout", a.storeHandler.Checkout)
	storeCustomer.GET("/store/orders", a.storeHandler.MyOrders)
	storeCustomer.GET("/store/orders/:id", a.storeHandler.GetMyOrder)
	storeCustomer.POST("/store/orders/:id/cancel", a.storeHandler.CancelMyOrder)
	storeCustomer.POST("/store/orders/:id/pay", a.storeHandler.InitiateOrderPayment)
	storeCustomer.POST("/store/payments/:id/complete", a.storeHandler.CompleteOrderPayment)

	customer := authenticated.Group("", sansyarmw.RequireRoles(auth.RoleCustomer, auth.RoleSuperAdmin))
	customer.POST("/bookings", a.bookingHandler.Create)
	customer.GET("/my/bookings", a.bookingHandler.MyBookings)
	customer.POST("/bookings/:id/cancel", a.bookingHandler.Cancel)
	customer.POST("/payments/initiate", a.paymentHandler.Initiate)
	customer.POST("/payments/verify", a.paymentHandler.Verify)
	customer.GET("/my/payments", a.paymentHandler.MyPayments)
	customer.GET("/wallet", a.walletHandler.Get)
	customer.GET("/wallet/transactions", a.walletHandler.Transactions)
	customer.POST("/wallet/topup", a.walletHandler.Topup)
	customer.POST("/bookings/:bookingId/reviews", a.reviewHandler.Create)
	customer.GET("/my/tickets", a.supportHandler.MyTickets)

	api.POST("/payments/webhook", a.paymentHandler.Webhook)

	owner := authenticated.Group("/owner", sansyarmw.RequireRoles(auth.RoleVenueOwner, auth.RoleVenueManager))
	owner.GET("/complexes", a.venueHandler.ListOwnerComplexes)
	owner.POST("/complexes", a.venueHandler.CreateComplex)
	owner.PATCH("/complexes/:id", a.venueHandler.UpdateComplex)
	owner.DELETE("/complexes/:id", a.venueHandler.DeleteComplex)
	owner.GET("/complexes/:complexId/halls", a.venueHandler.ListOwnerHalls)
	owner.POST("/complexes/:complexId/halls", a.venueHandler.CreateHall)
	owner.PATCH("/halls/:id", a.venueHandler.UpdateHall)
	owner.DELETE("/halls/:id", a.venueHandler.DeleteHall)
	owner.POST("/uploads", a.uploadHandler.Upload)
	owner.POST("/slots", a.venueHandler.CreateSlot)
	owner.PATCH("/slots/:id", a.venueHandler.UpdateSlot)
	owner.POST("/slots/bulk", a.venueHandler.CreateSlot)
	// Calendar-based session management.
	owner.GET("/sessions", a.venueHandler.ListSessions)
	owner.POST("/sessions", a.venueHandler.CreateSlot)
	owner.PATCH("/sessions/:id", a.venueHandler.UpdateSlot)
	owner.DELETE("/sessions/:id", a.venueHandler.DeleteSlot)
	owner.POST("/sessions/generate", a.venueHandler.GenerateSessions)
	owner.POST("/sessions/copy-day", a.venueHandler.CopyDay)
	owner.POST("/sessions/duplicate-week", a.venueHandler.DuplicateWeek)
	owner.POST("/sessions/bulk-update", a.venueHandler.BulkUpdateSessions)
	owner.POST("/sessions/block-range", a.venueHandler.BlockRange)
	owner.POST("/sessions/:id/manual-booking", a.bookingHandler.Create)
	owner.GET("/sessions/audit", a.venueHandler.SessionAudit)
	owner.GET("/bookings", a.bookingHandler.OwnerBookings)
	owner.POST("/bookings/manual", a.bookingHandler.Create)
	owner.POST("/bookings/:id/request-cancel", a.bookingHandler.RequestCancel)
	owner.GET("/payments", a.paymentHandler.MyPayments)
	owner.POST("/reviews/:id/reply", a.reviewHandler.Reply)
	owner.GET("/finance/summary", a.financeHandler.OwnerSummary)
	owner.GET("/finance/analytics", a.financeHandler.OwnerAnalytics)
	owner.GET("/finance/transactions", a.financeHandler.Transactions)

	admin := authenticated.Group("/admin", sansyarmw.RequireRoles(auth.RoleSuperAdmin))
	// Aggregated dashboard reads.
	admin.GET("/venues", a.adminHandler.ListVenues)
	admin.GET("/venues/:id", a.adminHandler.GetVenue)
	admin.GET("/owners", a.adminHandler.ListOwners)
	admin.GET("/owners/:id", a.adminHandler.GetOwner)
	admin.GET("/customers", a.adminHandler.ListCustomers)
	admin.GET("/customers/:id", a.adminHandler.GetCustomer)
	admin.GET("/users", a.authHandler.ListUsers)
	admin.POST("/users", a.authHandler.CreateUser)
	admin.PATCH("/users/:id", a.authHandler.UpdateUser)
	admin.DELETE("/users/:id", a.authHandler.SuspendUser)
	admin.POST("/users/:id/reset-password", a.authHandler.AdminResetPassword)
	admin.GET("/complexes", a.venueHandler.ListAdminComplexes)
	admin.POST("/complexes", a.venueHandler.AdminCreateComplex)
	admin.PATCH("/complexes/:id", a.venueHandler.AdminUpdateComplex)
	admin.DELETE("/complexes/:id", a.venueHandler.AdminDeleteComplex)
	admin.POST("/complexes/:id/approve", a.venueHandler.ApproveComplex)
	admin.POST("/complexes/:id/reject", a.venueHandler.RejectComplex)
	admin.POST("/complexes/:id/publish", a.venueHandler.PublishComplex)
	admin.POST("/complexes/:id/unpublish", a.venueHandler.UnpublishComplex)
	admin.GET("/halls", a.venueHandler.ListAdminHalls)
	admin.PATCH("/halls/:id", a.venueHandler.AdminUpdateHall)
	admin.DELETE("/halls/:id", a.venueHandler.AdminDeleteHall)
	admin.POST("/halls/:id/approve", a.venueHandler.ApproveHall)
	admin.POST("/halls/:id/reject", a.venueHandler.RejectHall)
	admin.POST("/halls/:id/publish", a.venueHandler.PublishHall)
	admin.POST("/halls/:id/unpublish", a.venueHandler.UnpublishHall)
	admin.POST("/uploads", a.uploadHandler.Upload)
	admin.GET("/sports", a.sportHandler.ListAdmin)
	admin.POST("/sports", a.sportHandler.Create)
	admin.PATCH("/sports/:id", a.sportHandler.Update)
	admin.DELETE("/sports/:id", a.sportHandler.Delete)
	admin.GET("/bookings", a.adminHandler.ListBookings)
	admin.GET("/bookings/:id", a.adminHandler.GetBooking)
	admin.POST("/bookings/:id/cancel", a.bookingHandler.AdminCancel)
	admin.POST("/bookings/:id/confirm", a.bookingHandler.AdminConfirm)
	admin.POST("/bookings/:id/approve-cancel", a.bookingHandler.ApproveCancel)
	admin.POST("/bookings/:id/reject-cancel", a.bookingHandler.RejectCancel)
	admin.POST("/reviews/:id/moderate", a.reviewHandler.Moderate)
	admin.GET("/finance/summary", a.financeHandler.AdminSummary)
	admin.GET("/finance/analytics", a.financeHandler.AdminAnalytics)
	admin.GET("/finance/settlements", a.financeHandler.Settlements)
	admin.GET("/support/tickets", a.supportHandler.List)
	admin.GET("/support/tickets/:id", a.supportHandler.Get)
	admin.PATCH("/support/tickets/:id/status", a.supportHandler.UpdateStatus)
	admin.POST("/support/tickets/:id/reply", a.supportHandler.Reply)

	// Store Admin: catalog management (products, categories, brands).
	admin.GET("/store/products", a.storeHandler.ListProductsAdmin)
	admin.POST("/store/products", a.storeHandler.CreateProduct)
	admin.GET("/store/products/:id", a.storeHandler.GetProductAdmin)
	admin.PATCH("/store/products/:id", a.storeHandler.UpdateProduct)
	admin.DELETE("/store/products/:id", a.storeHandler.DeleteProduct)
	admin.POST("/store/products/:id/publish", a.storeHandler.PublishProduct)
	admin.POST("/store/products/:id/unpublish", a.storeHandler.UnpublishProduct)
	// Variant management (SKU, price, stock, options).
	admin.POST("/store/products/:id/variants", a.storeHandler.CreateVariant)
	admin.PATCH("/store/variants/:id", a.storeHandler.UpdateVariant)
	admin.DELETE("/store/variants/:id", a.storeHandler.DeleteVariant)
	admin.GET("/store/categories", a.storeHandler.ListCategoriesAdmin)
	admin.POST("/store/categories", a.storeHandler.CreateCategory)
	admin.PATCH("/store/categories/:id", a.storeHandler.UpdateCategory)
	admin.DELETE("/store/categories/:id", a.storeHandler.DeleteCategory)
	admin.GET("/store/brands", a.storeHandler.ListBrandsAdmin)
	admin.POST("/store/brands", a.storeHandler.CreateBrand)
	admin.PATCH("/store/brands/:id", a.storeHandler.UpdateBrand)
	admin.DELETE("/store/brands/:id", a.storeHandler.DeleteBrand)
	// Dashboard, settings & customers.
	admin.GET("/store/stats", a.storeHandler.StatsAdmin)
	admin.PUT("/store/settings", a.storeHandler.UpdateSettingsAdmin)
	admin.GET("/store/customers", a.storeHandler.ListCustomersAdmin)
	// Coupons.
	admin.GET("/store/coupons", a.storeHandler.ListCouponsAdmin)
	admin.POST("/store/coupons", a.storeHandler.CreateCouponAdmin)
	admin.PATCH("/store/coupons/:id", a.storeHandler.UpdateCouponAdmin)
	admin.DELETE("/store/coupons/:id", a.storeHandler.DeleteCouponAdmin)
	// Order & inventory management.
	admin.POST("/store/variants/:id/stock", a.storeHandler.AdjustStock)
	admin.GET("/store/inventory", a.storeHandler.ListInventory)
	admin.GET("/store/inventory/logs", a.storeHandler.ListInventoryLogs)
	admin.GET("/store/orders", a.storeHandler.ListOrdersAdmin)
	admin.GET("/store/orders/:id", a.storeHandler.GetOrderAdmin)
	admin.PATCH("/store/orders/:id/status", a.storeHandler.UpdateOrderStatus)
}
